---
title: "HWFunction"
author: "Safiya Sayd"
format: pdf
---

## Simplier function for similar repetitive units 
```{r}
library(bio3d) 
s1 <- read.pdb("4AKE")  # kinase with drug 
s2 <- read.pdb("1AKE")  # kinase no drug 
s3 <- read.pdb("1E4Y")  # kinase with drug 
s1.chainA <- trim.pdb(s1, chain="A", elety="CA") 
s2.chainA <- trim.pdb(s2, chain="A", elety="CA") 
s3.chainA <- trim.pdb(s1, chain="A", elety="CA") 
s1.b <- s1.chainA$atom$b 
s2.b <- s2.chainA$atom$b 
s3.b <- s3.chainA$atom$b 
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor") 
```





```{r} 
#Generating a general function for repetitive sequences 
mypdb <- function(x) {
spdb <- read.pdb(x)
#Generating function called mypdbchain 
mypdbchain <- trim.pdb(spdb, chain="A", elety="CA") 

#Generating a function called chainatoms
chainatoms <- mypdbchain$atom$b

plotb3(chainatoms, sse=mypdbchain, typ="l", ylab="Bfactor")
}
```

```{r}
#Running Function
mypdb("4AKE")
```

```{r}
#Generating Multiple plots  
sapply (c("4AKE","1AKE", "1E4Y"), mypdb)
```

